version: "3.7"

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8083:8080"
    restart: unless-stopped
    command: sh /scripts/command.sh
    networks:
      - example

networks:
  example:




